# Generated by Django 2.2.3 on 2019-07-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connID', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('x_start', models.PositiveIntegerField()),
                ('x_end', models.PositiveIntegerField()),
                ('y_start', models.PositiveIntegerField()),
                ('y_end', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('duration', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
                ('vx', models.FloatField()),
                ('vy', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zoneID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('x_start', models.PositiveIntegerField()),
                ('x_end', models.PositiveIntegerField()),
                ('y_start', models.PositiveIntegerField()),
                ('y_end', models.PositiveIntegerField()),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_content.Room')),
            ],
            options={
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Obstruction',
            fields=[
                ('obsID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('x_start', models.PositiveIntegerField()),
                ('x_end', models.PositiveIntegerField()),
                ('y_start', models.PositiveIntegerField()),
                ('y_end', models.PositiveIntegerField()),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_content.Room')),
            ],
            options={
                'verbose_name_plural': 'Obstructions',
            },
        ),
    ]
