# Generated by Django 2.2.3 on 2019-07-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0002_auto_20190708_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name_plural': 'Connection'},
        ),
        migrations.AddField(
            model_name='connection',
            name='sampling',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
