# Generated by Django 2.2.3 on 2019-07-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0003_auto_20190710_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='sampling',
        ),
    ]
