# Generated by Django 2.2.3 on 2019-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0004_remove_connection_sampling'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='sampling',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
