# Generated by Django 2.2.3 on 2019-07-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0005_connection_sampling'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view_content.Tag')),
            ],
        ),
    ]
