# Generated by Django 2.2.3 on 2019-07-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0007_auto_20190710_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taglocations',
            options={'verbose_name_plural': 'locations'},
        ),
    ]
