# Generated by Django 2.2.3 on 2019-07-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0008_auto_20190710_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagLocations',
            new_name='TagLocation',
        ),
        migrations.AlterModelOptions(
            name='taglocation',
            options={'verbose_name_plural': 'taglocation'},
        ),
    ]
