# Generated by Django 2.2.3 on 2019-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0009_auto_20190710_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tagID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
