# Generated by Django 2.2.3 on 2019-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0010_auto_20190711_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='isconn',
            field=models.BooleanField(default=False),
        ),
    ]
