# Generated by Django 2.2.3 on 2019-09-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0011_connection_isconn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='isconn',
            new_name='connected',
        ),
    ]
