# Generated by Django 2.2.3 on 2019-10-12 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_content', '0012_auto_20190905_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name_plural': 'Session'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='session',
            name='status',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 12, 15, 41, 34, 236964)),
        ),
        migrations.AddField(
            model_name='taglocation',
            name='sessionID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='view_content.Session'),
            preserve_default=False,
        ),
    ]
